title: AI Mastery Journal
description: An experienced engineer going deep on AI.
author: Matias Burak
url: "https://mburak.github.io"
baseurl: "/ai-mastery"

theme: minima

permalink: /:year/:month/:day/:title/

header_pages:
  - about.md

show_excerpts: true

minima:
  skin: dark
