title: AI Mastery Journal
description: An experienced engineer's journey into AI engineering.
author: Matias Burak
url: "https://mburak.github.io"
baseurl: "/ai-mastery"

theme: minima

permalink: /:year/:month/:day/:title/

header_pages:
  - about.md

  minima:
    skin: dark
